[package]
name = "kodekraker"
version = "0.0.1"
authors = ["Victor Westerhuis <victor@westerhu.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
