comment_width = 80
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = true
match_block_trailing_comma = true
max_width = 100
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
required_version = "1.4.9"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
